/* This SPSS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME="C:\users\peiru\desktop\new folder (6)\13_countries\abs3w_cn.dat" LRECL=344 .

DATA LIST FILE=DATA/
   country 1                idnumber 2-5             level3 6              
   q1 7                     q2 8                     q3 9                  
   q4 10                    q5 11                    q6 12                 
   q7 13                    q8 14                    q9 15                 
   q10 16                   q11 17                   q12 18                
   q13 19                   q14 20                   q15 21                
   q16 22                   q17 23                   q18 24                
   q19 25                   q20 26                   q21 27                
   q22 28                   q23 29                   q24 30                
   q25 31                   q26 32                   q27 33                
   q28 34                   q29 35                   q30 36                
   q31 37                   q32 38                   q33 39                
   q33a 40                  q34 41                   q35 42                
   q36 43                   q37 44                   q38 45                
   q39 46                   q40 47                   q41 48-49             
   q42 50                   q43 51                   q44 52                
   q45 53                   q46 54                   q47 55                
   q48 56                   q49 57                   q50 58                
   q51 59                   q52 60                   q53 61                
   q54 62                   q55 63                   q56 64                
   q57 65                   q58 66                   q59 67                
   q60 68                   q61 69                   q62 70                
   q63 71                   q64 72                   q65 73                
   q66 74                   q67 75                   q68 76                
   q69 77                   q70 78                   q71 79                
   q72 80                   q73 81                   q74 82                
   q74a 83                  q75 84                   q75a 85               
   q76 86                   q76a 87                  q77 88                
   q77a 89                  q78 90                   q78a 91               
   q79 92                   q79a 93                  q80 94                
   q81 95                   q82 96                   q83 97                
   q84 98                   q85 99                   q86 100               
   q87 101                  q88 102                  q89 103               
   q90 104                  q91 105-106              q92 107-108           
   q93 109-110              q94 111-112              q95 113               
   q96 114                  q97 115                  q98 116               
   q99 117                  q100 118                 q101 119              
   q102 120                 q103 121                 q104 122              
   q105 123                 q106 124                 q107 125              
   q108 126                 q109 127                 q110 128              
   q111 129                 q112 130                 q113 131              
   q114 132                 q115 133                 q116 134              
   q117 135                 q118 136                 q119 137              
   q119_1 138               q119_2 139               q119_3 140            
   q120 141-142             q121 143-144             q122 145-146          
   q123 147-148             q124 149                 q125 150              
   q126 151                 q127 152                 q128 153              
   q129 154                 q130 155                 q131 156              
   q132 157                 q133 158                 q134 159              
   q135 160                 q136 161                 q137 162              
   q138 163                 q139 164                 q140 165              
   q141 166                 q142 167                 q143 168              
   q144 169                 q145 170                 q146 171              
   q147 172                 q148 173                 q149 174              
   q150 175                 q151 176                 q152 177              
   q153 178                 q154 179                 q155 180              
   q156 181-182             q157 183                 q157a 184             
   q158 185-186             q159 187-188             q160 189              
   q161 190                 se2 191                  se3 192-195           
   se3a 196-197             se4 198                  se5 199-200           
   se5a 201-203             se6 204-205              se7 206-207           
   se7a 208-209             se8a 210-211             se8b 212              
   se8c 213                 se8d 214                 se9 215               
   se9a 216                 se9b 217                 se9c 218              
   se9d 219                 se9e 220                 se10 221              
   se10_1 222               se10a 223                se10b 224             
   se10c 225                se10d 226                se10e 227             
   se11 228                 se12 229-230             se13 231              
   se13a 232                se14a 233                se14b 234             
   se14c 235                se14d 236                se14e 237             
   se14f 238                se14g 239                se14h 240             
   se14i 241                se14j 242                se14k 243             
   se14l 244                se14m 245                se14n 246             
   se14o 247                ir1 248-250              ir2 251               
   ir2a 252                 ir2b 253-254             ir2c 255-257          
   ir3 258                  ir3a 259                 ir3a_1HK 260          
   ir3a_2HK 261             ir3a_3HK 262             ir3a_4HK 263          
   ir3a_5HK 264             ir4 265                  ir5 266               
   ir6 267                  ir7 268                  ir8 269               
   ir9 270-280 (DATE)       ir10 281                 ir10a 282             
   ir11a 283                ir11b 284                ir11c 285             
   ir11d 286                ir12 287                 ir12a 288             
   ir12b 289                ir12c 290                ir12d 291             
   ir12e 292                ir12f 293                ir12g 294             
   ir12h 295                ir12i 296                ir12k 297             
   ir13 298                 INCOMEALL 299-308        CNweight 309-326      
   allweight 327-344 .   


FORMATS
  se5a (F4.1) /            ir9 (F12.11) /           INCOMEALL (F11.2) /    
  CNweight (F19.16) /      allweight (F19.16) / .

VARIABLE LABELS
   country 'Country Code'
   idnumber 'case number'
   level3 'urban-rural'
   q1    'q1. How would you rate the overall economic condition of our coun' +
   'try today?  Is it ¡K'
   q2    'q2. How would you describe the change in the economic condition o' +
   'f our country over the last few years'
   q3    "q3. What do you think will be the state of our country's economic" +
   " condition a few years from now? Will it be ¡K"
   q4    'q4. As for your own family, how do you rate the economic situatio' +
   'n of your family today?  Is it ¡K'
   q5    'q5. How would you compare the current economic condition of your ' +
   'family with what it was a few years ago? Is it ¡K'
   q6    'q6. What do you think the economic situation of your family will ' +
   'be a few years from now? Will it be ¡K'
   q7    "q7. I'm going to name a number of institutions. For each one, ple" +
   "ase tell me how much trust do you have in them? The president"
   q8 'q8. The courts'
   q9 'q9. The national government [in capital city]'
   q10 'q10. Political parties [not any specific party]'
   q11 'q11. Parliament'
   q12 'q12. Civil service'
   q13 'q13. The military(or armed forces)'
   q14 'q14. The police'
   q15 'q15. Local government'
   q16 'q16. Newspapers'
   q17 'q17. Television'
   q18    'q18. The election commission [specify institution by name] <Optio' +
   'nal>'
   q19 'q19. Non-governmental organizations or NGOs <Optional>'
   q20    'q20. Could you identity the three most important organizations or' +
   ' formal groups you belong to. First Organization'
   q21 'q21. Second Organization'
   q22 'q22. Third Organization'
   q23    'q23. General speaking, would you say that "Most people can be tru' +
   'sted" or "that you must be very careful in dealing with people"?'
   q24    'q24. Do you think most people would try to take advantage of you ' +
   'if they got a chance, or would they try to be fair? (NEW)'
   q25    'q25. How much trust do you have in each of the following types of' +
   ' people?   Your relatives'
   q26 'q26. Your neighbors'
   q27 'q27. Other people you interact with'
   q28    'q28. On average, about how many people do you have contact with i' +
   'n a typical week day?  We are interested in contact on a one-on-o' +
   'ne basis, including everyone with whom you chat, talk, or discuss' +
   ' matters.  This can be face to face, by telephone, by mail,'
   q29    'q29. If you have a difficult problem to manage, are there people ' +
   'outside your household you can ask for help? (NEW)'
   q30    'q30. When people outside your household have problems, do they co' +
   'me to you for help? (NEW)'
   q31    'q31. If you had friends or co-workers whose opinions on politics ' +
   'differed from yours, would you have a hard time conversing with t' +
   'hem? (NEW)'
   q32    "q32. In talking to people about elections, we often find that a l" +
   "ot of people were not able to vote because they were away from ho" +
   "me, they were sick or they just didn't have time. How about you? " +
   "Did you vote in the election [the most recent national elect"
   q33    'q33. Which parties (or candidates for president if it was preside' +
   'ntial race) did you vote for? [country-specific response grid]'
   q33a    'q33a. Based on the answer to Q33, please construct a new variable' +
   ' indicating if the respondent voted for the winning camp or losin' +
   'g camp.'
   q34    'q34. Thinking about the national election in [year], did you atte' +
   'nd a campaign meeting or rally?'
   q35    'q35. try to persuade others to vote for a certain candidate or pa' +
   'rty?'
   q36    'q36. Did you do anything else to help out or work for a party or ' +
   'candidate running in the election?'
   q37    'q37. On the whole, how free and fair would you say the last natio' +
   'nal election was? (NEW)'
   q38    'q38. Based on your experience, how easy or difficult is it to obt' +
   'ain the following services?  Or have you never tried to get these' +
   ' services from government?  An identity document (such as a birth' +
   ' certificate or passport)'
   q39 'q39. A place in a public primary school for a child'
   q40 'q40. Medical treatment at a nearby clinic'
   q41 'q41. Help from the police when you need it'
   q42    'q42. Generally speaking, how safe is living in this city/ town/ v' +
   'illage - very safe, safe, unsafe or very unsafe?'
   q43 'q43. How interested would you say you are in politics?'
   q44 'q44. How often do you follow news about politics and government?'
   q45 'q45. How often do you use the internet?'
   q46    'q46. When you get together with your family members or friends, h' +
   'ow often do you discuss political matters?'
   q47    'q47. Among the political parties listed here, which party if any ' +
   'do you feel closest to?'
   q48    'q48. How close do you feel to (answer in Q47)? Is it very close, ' +
   'somewhat close, or just a little close?'
   q49    'q49. Please tell me how you feel about the following statements. ' +
   'Would you say you strongly agree, somewhat agree, somewhat disagr' +
   'ee, or strongly disagree? Most people are trustworthy?'
   q50    'q50. For the sake of the family, the individual should put his pe' +
   'rsonal interests second'
   q51    "q51. In a group, we should sacrifice our individual interest for " +
   "the sake of the group's collective interest."
   q52    'q52. For the sake of national interest, individual interest could' +
   ' be sacrificed.'
   q53    "q53. When dealing with others, developing a long-term relationshi" +
   "p is more important than securing one's immediate interest."
   q54    'q54. When dealing with others, one should not only focus on immed' +
   'iate interest but also plan for future.'
   q55    "q55. Even if parents' demands are unreasonable, children still sh" +
   "ould do what they ask."
   q56    'q56. When a mother-in-law and a daughter-in-law come into conflic' +
   't, even if the mother-in-law is in the wrong, the husband should ' +
   'still persuade his wife to obey his mother.'
   q57    'q57. Being a student, one should not question the authority of th' +
   'eir teacher.'
   q58    'q58. In a group, we should avoid open quarrel to preserve the har' +
   'mony of the group'
   q59    'q59. Even if there is some disagreement with others, one should a' +
   'void the conflict'
   q60    'q60. A person should not insist on his own opinion if his co-work' +
   'ers disagree with him'
   q61    'q61. Wealth and poverty, success and failure are all determined b' +
   'y fate.'
   q62    'q62. If one could have only one child, it is more preferable to h' +
   'ave a boy than a girl.'
   q63    'q63. When dealing with others, one should not be preoccupied with' +
   ' temporary gains and losses.'
   q64    'q64. In the past three (3) years, have you never, once, or more t' +
   'han once done the following because of personal, family, or neigh' +
   'borhood problems, or problems with government officials and polic' +
   'ies?Contacted elected officials or legislative representativ'
   q65 'q65. Contacted officials at higher level.'
   q66 'q66. Contacted traditional leaders/community leaders.'
   q67 'q67. Contacted other influential people outside the government'
   q68 'q68. Contacted news media'
   q69    'q69. Here is a list of actions that people sometimes take as citi' +
   'zens. For each of these, please tell me whether you, personally, ' +
   'have never, once, or more than once done any of these things duri' +
   'ng the past three years.   Got together with others to try t'
   q70    'q70. Got together with others to raise an issue or sign a petitio' +
   'n'
   q71 'q71. Attended a demonstration or protest march'
   q72 'q72. Used force or violence for a political cause'
   q73    'q73. Thinking of whether you voted or not ever since you became e' +
   'ligible for voting, how would you describe yourself -have you vot' +
   'ed in every election, voted in most elections, voted in some elec' +
   'tions or hardly ever voted?'
   q74    "q74. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q74a    'q74a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q75    "q75. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q75a    'q75a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q76    "q76. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q76a    'q76a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q77    "q77. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q77a    'q77a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q78    "q78. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q78a    'q78a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q79    "q79. Let's talk for a moment about the kind of government you wou" +
   "ld like to have in this country, which of the followings statemen" +
   "ts do you agree with most? Choose the first or the second stateme" +
   "nt. [Interviewer: Probe whether respondent strongly agrees o"
   q79a    'q79a. Do you strongly agree or just agree with the chosen stateme' +
   'nt?'
   q80    'q80. Over the long run, our system of government is capable of so' +
   'lving the problems our country faces.'
   q81    'q81. Thinking in general, I am proud of our system of government.'
   q82    "q82. A system like ours, even if it runs into problems, deserves " +
   "the people's support."
   q83    'q83. I would rather live under our system of government than any ' +
   'other that I can think of.'
   q84    'q84. Compared with other systems in the world, would you say our ' +
   'system of government works fine as it is, needs minor change, nee' +
   'ds major change, or should be replaced?'
   q85    'q85. Many things may be desirable, but not all of them are essent' +
   'ial characteristics of democracy. If you have to choose only one ' +
   'from each four sets of statements that I am going to read, which ' +
   'one would you choose as the most essential characteristics o'
   q86    'q86. If you have to choose only one from each four sets of statem' +
   'ents that I am going to read, which one would you choose as the m' +
   'ost essential characteristics of a democracy?'
   q87    'q87. If you have to choose only one from each four sets of statem' +
   'ents that I am going to read, which one would you choose as the m' +
   'ost essential characteristics of a democracy?'
   q88    'q88. If you have to choose only one from each four sets of statem' +
   'ents that I am going to read, which one would you choose as the m' +
   'ost essential characteristics of a democracy?'
   q89    'q89. On the whole, how satisfied or dissatisfied are you with the' +
   ' way democracy works in [Country].  Are you ¡K?'
   q90 'q90. In your opinion how much of a democracy is [Country Name] ?'
   q91    'q91. Here is a scale: 1 means completely undemocratic and 10 mean' +
   's completely democratic. Where would you place our country under ' +
   'the present government?'
   q92 'q92. Where would you place our country ten years ago?'
   q93 'q93. Where would you want our country to be in the future?'
   q94    'q94. Here is a similar scale of 1 to 10 measuring the extent to w' +
   'hich people think democracy is suitable for our country. If "1" m' +
   'eans that democracy is completely unsuitable for [name of country' +
   '] today and "10" means that it is completely suitable, where'
   q95    'q95. How satisfied or dissatisfied are you with the [name of pres' +
   'ident, etc. ruling current] government?  Are you ¡K?'
   q96    'q96. In your opinion, what are the most important problems facing' +
   ' this country that government should address?'
   q97    'q97. How likely is it that the government will solve the most imp' +
   'ortant problem you identified within the next five years? [Read o' +
   'ut options]'
   q98    'q98. Now I am going to read to you a list of statements that desc' +
   'ribe how people often feel about the state of affairs in [country' +
   ' name]. Please tell me whether you strongly agree, somewhat agree' +
   ', somewhat disagree, or strongly disagree with each of these'
   q99    'q99. Political parties or candidates in our country have equal ac' +
   'cess to the mass media during the election period.'
   q100    'q100. Between elections, the people have no way of holding the go' +
   'vernment responsible for its actions.'
   q101    'q101. When government leaders break the laws, there is nothing th' +
   'e court can do.'
   q102    "q102. Most citizens in our country don't make much effort to infl" +
   "uence government decisions."
   q103    'q103. All citizens from different ethnic communities in Country X' +
   ' are treated equally by the government.'
   q104    'q104. Rich and poor people are treated equally by the government.'
   q105    'q105. People have basic necessities like food, clothes, and shelt' +
   'er.'
   q106 'q106. People are free to speak what they think without fear.'
   q107 'q107. People can join any organization they like without fear.'
   q108 'q108. Do officials who commit crimes go unpunished?'
   q109    'q109. How often do government officials withhold important inform' +
   'ation from the public view?'
   q110    'q110. How often do you think government leaders break the law or ' +
   'abuse their power?'
   q111    'q111.  How often do you think our elections offer the voters a re' +
   'al choice between different parties/candidates?'
   q112    'q112. To what extent is the legislature capable of keeping govern' +
   'ment leaders in check?'
   q113    'q113. How well do you think the government responds to what peopl' +
   'e want?'
   q114    'q114. In your neighborhood or community, do people voice their in' +
   'terests and concerns in local affairs?'
   q115    'q115. How much do you feel that having elections makes the govern' +
   'ment pay attention to what the people think?'
   q116    'q116. How widespread do you think corruption and bribe-taking are' +
   ' in your local/municipal government?  Would you say ¡K?'
   q117    'q117. How widespread do you think corruption and bribe-taking are' +
   ' in the national government [in capital city]?  Would you say ¡K?'
   q118    'q118. In your opinion, is the government working to crack down on' +
   ' corruption and root out bribery?'
   q119    'q119. Have you or anyone you know personally witnessed an act of ' +
   'corruption or bribe-taking by a politician or government official' +
   ' in the past year? IF WITNESSED: Did you personally witness it or' +
   ' were you told about it by a family member or friend who per'
   q119_1 '119_1 Personally witnessed'
   q119_2 '119_2 Told about it by family member'
   q119_3 '119_3 Told about it by friend'
   q120    'q120. Remember the scale that we used before: 1 means completely ' +
   'undemocratic and 10 means completely democratic. Where would you ' +
   'place China today on this scale?'
   q121    'q121. Where would you place the United States today on this scale' +
   '?'
   q122 'q122. Where would you place Japan today on this scale?'
   q123 'q123. Where would you place India today on this scale?'
   q124    'q124. Which of the following statements comes closest to your own' +
   ' opinion?'
   q125    'q125. Which of the following statements comes closer to your own ' +
   'view?'
   q126    'q126. If you had to choose between democracy and economic develop' +
   'ment, which would you say is more important?'
   q127    'q127. If you had to choose between reducing economic inequality a' +
   'nd protecting political freedom, which would you say is more impo' +
   'rtant?'
   q128    'q128. Do you agree or disagree with the following statement: "Dem' +
   'ocracy may have its problems, but it is still the best form of go' +
   'vernment."'
   q129    'q129. There are many ways to govern a country. Would you disappro' +
   've or approve of the following alternatives? For each statement, ' +
   'would you say you strongly approve, approve, disapprove, or stron' +
   'gly disapprove? We should get rid of parliament and election'
   q130    'q130. Only one political party should be allowed to stand for ele' +
   'ction and hold office.'
   q131 'q131. The army (military) should come in to govern the country.'
   q132    'q132. We should get rid of elections and parliaments and have exp' +
   'erts make decisions on behalf of the people.'
   q133    'q133. I have here some statements. For each statement, would you ' +
   'say you strongly agree, somewhat agree, somewhat disagree, or str' +
   'ongly disagree? I think I have the ability to participate in poli' +
   'tics.'
   q134    "q134. Sometimes politics and government seems so complicated that" +
   " a person like me can't really understand what is going on."
   q135    "q135. People like me don't have any influence over what the gover" +
   "nment does."
   q136    'q136. You can generally trust the people who run our government t' +
   'o do what is right.'
   q137    'q137. A citizen should always remain loyal only to his country, n' +
   'o matter how imperfect it is or what wrong it has done.'
   q138    'q138. I have here other statements. For each statement, would you' +
   ' say you strongly agree, somewhat agree, somewhat disagree, or st' +
   'rongly disagree? The government should consult religious authorit' +
   'ies when interpreting the laws.'
   q139 'q139. Women should not be involved in politics as much as men.'
   q140    'q140. People with little or no education should have as much say ' +
   'in politics as highly-educated people.'
   q141    'q141. Government leaders are like the head of a family; we should' +
   ' all follow their decisions.'
   q142    'q142. The government should decide whether certain ideas should b' +
   'e allowed to be discussed in society.'
   q143    'q143. Harmony of the community will be disrupted if people organi' +
   'ze lots of groups.'
   q144    'q144. When judges decide important cases, they should accept the ' +
   'view of the executive branch.'
   q145    'q145. If the government is constantly checked [i.e. monitored and' +
   ' supervised] by the legislature, it cannot possibly accomplish gr' +
   'eat things.'
   q146    'q146. If we have political leaders who are morally upright, we ca' +
   'n let them decide everything.'
   q147    'q147. If people have too many different ways of thinking, society' +
   ' will be chaotic.'
   q148    'q148. When the country is facing a difficult situation, it is ok ' +
   'for the government to disregard the law in order to deal with the' +
   ' situation.'
   q149    'q149. How closely do you follow major events in foreign countries' +
   ' / the world?'
   q150    'q150. How often do you watch or listen to foreign programs (telev' +
   'ision, DVDs, movies, radio)?'
   q151    'q151. Our country should defend our way of life instead of becomi' +
   'ng more and more like other countries.'
   q152    'q152. Do you agree or disagree with the following statement: "We ' +
   'should protect our farmers and workers by limiting the import of ' +
   'foreign goods."'
   q153    'q153. Do you agree or disagree with the following statement: "For' +
   'eign goods are hurting the local community."'
   q154 'q154. How proud are you to be a citizen of (COUNTRY)?'
   q155    'q155. Given the chance, how willing would you be to go and live i' +
   'n another country?'
   q156 'q156. Which country has the most influence in Asia?'
   q157    'q157. Does (answer in Q156) do more good or harm to the region? A' +
   'sk Q157a if the answer in Q156 is not China, otherwise skip to Q1' +
   '58'
   q157a 'q157a. Does China do more good or harm to the region?'
   q158    'q158. In ten years, which country will have the most influence in' +
   ' Asia?'
   q159    "q159. Which country should be a model for our own country's futur" +
   "e development?"
   q160 'q160. How much influence does China have on our country?'
   q161    'q161. General speaking, the influence China has on our country is' +
   '?'
   se2 'SE2. GENDER'
   se3 'SE3. BIRTH YEAR'
   se3a 'SE3a.ACTUAL AGE'
   se4 'SE4. MARITAL STATUS'
   se5 'SE5. EDUCATION'
   se5a 'SE5a. How many years of formal education you have received?'
   se6 'SE6. RELIGION'
   se7    'SE7. RELIGIOSITY: About how often do you practice religious servi' +
   'ces or rituals these days?'
   se7a    'SE7a. Would you describe yourself as very religious, moderately r' +
   'eligious, lightly religious, not religious at all?'
   se8a 'SE8a. How many people live in this household?'
   se8b    'SE8b. How many generations of family members live in this househo' +
   'ld?'
   se8c 'Actual count(INCLUDE servants, transients/boarders)'
   se8d 'Actual count(EXCLUDE servants, transients/boarders)'
   se9 'SE9. Are you currently employed?(respondent)'
   se9a    'SE9a. Are you currently self-employed (including business owners)' +
   ', working in a family business, or working for an outside emp'
   se9b 'SE9b. How many people does your business employ?'
   se9c    'SE9c. What is your job title and job description?<The code number' +
   ' of ISCO>'
   se9d 'SE9d. Are you currently seeking employment?'
   se9e 'SE9e. What is your current status?'
   se10    'SE10. Are you the main earner in your household?(Chief wage earne' +
   'r)<Optional>'
   se10_1 'SE10_1. Is the main earner in your household currently employed?'
   se10a    'SE10a. Is he or she currently self-employed (including business o' +
   'wners), working in a family business, or working for an outsid'
   se10b 'SE10b. How many people do his or her business employ?'
   se10c    'SE10c. What is his or her job title and job description?<The code' +
   ' number of ISCO>'
   se10d 'SE10d. Is he or she currently seeking employment?'
   se10e 'SE10e. What is his or her current status?'
   se11 'SE11. LANGUAGE: What language do you speak the most in the home?'
   se12 'SE12. SUBJECTIVE SOCIAL STATUS'
   se13 'SE13. HOUSEHOLD INCOME'
   se13a    'SE13a. Does the total income of your household allow you to satis' +
   'factorily cover your needs?'
   se14a 'SE14a. Car/Jeep/Van'
   se14b 'SE14b. Tractor'
   se14c 'SE14c. Television'
   se14d 'SE14d. Cable Television'
   se14e 'SE14e. Motorcycle'
   se14f 'SE14f. Telephone'
   se14g 'SE14g. Mobile Phone'
   se14h 'SE14h. Electric Fan'
   se14i 'SE14i. Bicycle'
   se14j 'SE14j. Radio'
   se14k 'SE14k. Pumping Set'
   se14l 'SE14l. Fridge'
   se14m 'SE14m. Camera'
   se14n 'SE14n. Goats/Sheep'
   se14o 'SE14o. Cow/Buffalo'
   ir1 "IR1. Interviewer's number"
   ir2 'IR2. Is this the first questionnaire you have completed?'
   ir2a "IR2a. Interviewer's gender"
   ir2b "IR2b. Interviewer's Age"
   ir2c    'IR2c. What kind of language do you normally use at home?[Country-' +
   'specific]'
   ir3    'IR3. In the interview, other than the respondent, were others pre' +
   'sent?'
   ir3a 'Who were they? (Multiple answers allowed)'
   ir3a_1HK '	Respondent¡¦s spouse'
   ir3a_2HK '	Children '
   ir3a_3HK '	Parents or parents-in-law'
   ir3a_4HK '	Neighbors/Passers by '
   ir3a_5HK '	Party/Government Official'
   ir4    'IR4. Has the respondent ever refused to be interviewed during the' +
   ' whole process?'
   ir5    'IR5. Has the respondent ever felt impatient during the interview?'
   ir6 'IR6. How cooperative was the respondent during the interview?'
   ir7    'IR7. How sincere was the respondent when answering sensitive ques' +
   'tions?'
   ir8    'IR8. What proportion of the questions do you feel the respondent ' +
   'had difficulty answering?'
   ir9 'Date of Interview____(month)____(date)_2010_(year)'
   ir10 'IR10. Language in which interview was conducted'
   ir10a    'IR10a. Was the interview conducted with the assistance of an inte' +
   'rpreter?'
   ir11a    "IR11a. What is the condition of the road leading to interviewee's" +
   " residence?"
   ir11b    'IR11b. Please identify the main source of drinking water in the h' +
   'ousehold?'
   ir11c 'IR11c. Is electricity the main source of lighting in the house?'
   ir11d    "IR11d. In terms of walking distance, how far is it between the ne" +
   "arest public transportation stop (bus, train, ferry, tram, etc) a" +
   "nd the respondent's house?"
   ir12    'IR12. Were the following services present within the neighborhood' +
   ' (i.e., within walking or easy driving distance).Estimate the dis' +
   'tance of these services by:'
   ir12a 'IR12a. Post-office'
   ir12b 'IR12b. School'
   ir12c 'IR12c. Police station'
   ir12d 'IR12d. Sewerage system that most houses could access'
   ir12e 'IR12e. Health clinic'
   ir12f 'IR12f. Signal for cellular phone'
   ir12g 'IR12g. Recreational facilities, e.g., a sports field'
   ir12h    'IR12h. Any churches, mosques, temples or other public places of w' +
   'orship'
   ir12i    'IR12i. Any town halls or community buildings that can be used for' +
   ' meetings'
   ir12k 'IR12k. Market stalls (selling groceries and/or clothing)'
   ir13    'IR13. Which of the following levels within the country the respon' +
   'dent live?'
   CNweight 'weight for Mainland China'
   allweight 'all country weights (= JPweight, ..., MAweight)' .

VALUE LABELS
 country
     1 'Japan'
     2 'Hong Kong'
     3 'Korea'
     4 'Mainland China'
     5 'Mongolia'
     6 'Philippines'
     7 'Taiwan'
     8 'Thailand'
     9 'Indonesia'
     10 'Singapore'
     11 'Vietnam'
     12 'Cambodia'
     13 'Malaysia' /
 level3
     1 'urban'
     2 'rural' /
 q1 q4
     1 'Very good'
     2 'Good'
     3 'So so (not good nor bad)'
     4 'Bad'
     5 'Very bad'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q2 q3 q6
     1 'Much better'
     2 'A little better'
     3 'About the same'
     4 'A little worse'
     5 'Much worse'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q5
     1 'Much better now'
     2 'A little better now'
     3 'About the same'
     4 'A little worse now'
     5 'Much worse now'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answe' /
 q7 q8 q9 q10 q11 q12 q13 q14 q15 q16 q17 q18 q19
     1 'A great deal of trust'
     2 'Quite a lot of trust'
     3 'not very much trust not very much trust'
     4 'None at all'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q20
     1 'Political parties'
     2 'Residential & community associations'
     3 'Religious groups'
     4 'Sports/ recreational clubs'
     5 'Culture organizations'
     6 'Charities'
     7 'Public interest groups'
     8 'Labor unions'
     9 'Farmer unions or agricultural associations'
     10 'Professional organizations'
     11 'Business associations'
     12 'Parent-Teacher Associations or PTA'
     13 'Producer cooperatives'
     14 'Consumer cooperatives'
     15 'Alumni associations'
     16 'Candidate support organizations'
     17 'Other occupational organizations (etc.)'
     18 'Other volunteer organizations'
     19 'Volunteer police and firefighters'
     20 'Can association'
     21 "Women's association"
     22 'Hometown association'
     23 'Peer group'
     90 'Not a member of any organization or group'
     98 "Can't choose"
     99 'Decline to answer'
     100 'Not applicable' /
 q21
     1 'Political parties'
     2 'Residential & community associations'
     3 'Religious groups'
     4 'Sports/ recreational clubs'
     5 'Culture organizations'
     6 'Charities'
     7 'Public interest groups'
     8 'Labor unions'
     9 'Farmer unions or agricultural associations'
     10 'Professional organizations'
     11 'Business associations'
     12 'Parent-Teacher Associations or PTA'
     13 'Producer cooperatives'
     14 'Consumer cooperatives'
     15 'Alumni associations'
     16 'Candidate support organizations'
     17 'Other occupational organizations (etc.)'
     18 'Other volunteer organizations'
     19 'Volunteer police and firefighters'
     20 'Can association'
     21 "Women's association"
     22 'Hometown association'
     23 'Peer group'
     90 'Not a member of any organization or group'
     99 'Decline to answer'
     100 'Not applicable' /
 q22
     1 'Political parties'
     2 'Residential & community associations'
     3 'Religious groups'
     4 'Sports/ recreational clubs'
     5 'Culture organizations'
     6 'Charities'
     7 'Public interest groups'
     8 'Labor unions'
     9 'Farmer unions or agricultural associations'
     10 'Professional organizations'
     11 'Business associations'
     12 'Parent-Teacher Associations or PTA'
     13 'Producer cooperatives'
     14 'Consumer cooperatives'
     15 'Alumni associations'
     16 'Candidate support organizations'
     17 'Other occupational organizations (etc.)'
     18 'Other volunteer organizations'
     19 'Volunteer police and firefighters'
     20 'Can association'
     21 "Women's association"
     22 'Hometown association'
     90 'Not a member of any organization or group'
     98 "Can't choose"
     99 'Decline to answer'
     100 'Not applicable' /
 q23
     1 'Most people can be trusted'
     2 'You must be very careful in dealing with people'
     6 '"It depends"'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q24
     1 'Most people would try to take advantage of you if they got a'
     2 'Most people would try to be fair'
     6 '"It depends"'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q25 q26 q27
     1 'A great deal of Trust'
     2 'Quite a lot of Trust'
     3 'Not very much Trust'
     4 'None at all'
     7 'Do not understand'
     8 "Can't choose"
     9 'Decline to answer' /
 q28
     0 ' Not applicable'
     1 '0-4 people'
     2 '5-9 people'
     3 '10-19 people '
     4 '20-49 people'
     5 '50 or more people'
     8 "Can't choose"
     9 'Decline to answer' /
 q29
     1 'No, nobody'
     2 'Yes, a few'
     3 'Yes, some '
     4 'Yes, a lot'
     7 'Do not understand the question'
     8 "Can't choose"
     9 ' Decline to answer' /
 q30
     1 'No, nobody'
     2 'Yes, a few'
     3 'Yes, some '
     4 'Yes, a lot'
     7 ' Do not understand the question'
     8 "Can't choose"
     9 ' Decline to answer' /
 q31
     1 'Very hard'
     2 'A bit hard'
     3 'Not too hard'
     4 'Not hard at all'
     7 'Do not understand the question'
     8 "Can't choose"
     9 " Don't respond" /
 q32
     0 'Not applicable'
     1 'Yes'
     2 'No'
     3 'not eligible to vote'
     8 "Can't choose"
     9 'Decline to answer' /
 q33
     90 'Not applicable'
     92 'No vote'
     97 "Dont' know"
     98 "Can't choose"
     99 'Decline to answer'
     101 'DPJ'
     102 'LDP'
     103 'CGP'
     104 'Minna'
     105 'JCP'
     106 'SDP'
     107 'others'
     108 'independent'
     201 'DP(HK)'
     202 'DAB(HK)'
     203 'Liberal PArty(HK)'
     204 'Civic Party(HK)'
     205 'FTU(HK)'
     206 "New People's Party(HK)"
     207 'ADPL(HK)'
     208 'LSD(HK)'
     209 'People Power(HK)'
     210 'Labour Party(HK)'
     211 'NeoDemocrats(HK)'
     212 'NWSC(HK)'
     214 'Others(HK)'
     301 'Chung Dong-young'
     302 'Lee Myung-bak'
     303 'Kwon Young-ghil'
     304 'Rhee In-je'
     305 'Moon Kook-hyun'
     306 'Lee Hoi- chang'
     307 'Others'
     308 "Can't choose"
     309 'Decline to answer'
     501 'N. Enhbayar'
     505 'Ts. Elbegdorj'
     601 "Lacson, Panfilo Morena ''Ping''"
     602 "Macapagal-Arroyo, Gloria Macaraeg ''GMA''"
     603 "Poe, Fernando, Jr/Ronald Allan Kelley ''FPJ''"
     605 "Villanueva, Eduardo Cruz ''Bro. Eddie''"
     606 'Others'
     607 'None'
     701 'Hsieh Chang-ting and Su Tseng-chang'
     702 'Ma Ying-jeou and Vincent Siew'
     703 'Cast invalid vote'
     801 'Phak Prachatipat'
     802 'Phak Puea Tha'
     803 'Phak Bhum Jai Thai'
     804 'Phak Chart Thai Pattana'
     805 'Phak Pua Paendin'
     806 'Phak Ruam Jai Thai Chat Pattana'
     807 'Phak Chart Thai'
     808 'Phak Thai rak Thai'
     809 'Phak Pracharat'
     810 'Phak Palang Prachachon'
     811 'Phak Puea Prachachon'
     901 'Partai Hanura'
     902 'Partai Karya Peduli Bangsa (PKPB)'
     903 'Partai Pengusaha dan Pekerja Indonesia'
     904 'Partai Peduli Rakyat Nasional'
     905 'Partai Gerindra'
     906 'Partai Barisan Nasional'
     907 'Partai Keadilan dan Persatuan Indonesia'
     908 'Partai Keadilan Sejahtera (PKS)'
     909 'Partai Amanat Nasional (PAN)'
     910 'Partai Perjuangan Indonesia Baru (PIB)'
     911 'Partai Kedaulatan'
     912 'Partai Persatuan Daerah (PPD)'
     913 'Partai Kebangkitan Bangsa (PKB)'
     914 'Partai Pemuda Indonesia'
     915 'Partai Nasional Indonesia Marhaenisme'
     916 'Partai Demokrasi Pembaruan (PDP)'
     917 'Partai Karya Perjuangan'
     918 'Partai Matahari Bangsa'
     919 'Partai Penegak Demokrasi Indonesia'
     920 'Partai Demokrasi Kebangsaan'
     921 'Partai Republik Nusantara'
     922 'Partai Pelopor'
     923 'Partai Golongan Karya'
     924 'Partai Persatuan Pembangunan'
     925 'Partai Damai Sejahtera (PDS)'
     926 'Partai Nasional Benteng Kerakyatan Indonesia (PNBKI)'
     927 'Partai Bulan Bintang (PBB)'
     928 'Partai Demokrasi Indonesia Perjuangan (PDIP)'
     929 'Partai Bintang Reformasi (PBR)'
     930 'Partai Patriot'
     931 'Partai Demokrat'
     932 'Partai Kasih Demokrasi Indonesia (PKDI)'
     933 'Partai Indonesia Sejahtera'
     934 'Partai Kebangkitan Nasional Ulama (PKNU)'
     941 'Partai Merdeka'
     942 'Partai Persatuan Nahdlatul Ummah Indonesia'
     943 'Partai Sarikat Indonesia'
     944 'Partai Buruh'
     1201 'Norodom Ranariddh Party'
     1202 "Cambodian People's Party"
     1203 'Funcinpec'
     1204 'Sam Rainsy Party'
     1205 'League for Democracy Party'
     1206 'Human Rights Party'
     1207 'Khmer Democratic Party'
     1208 'Khmer Anti-Poverty Party'
     1209 'Khmer Republican Party'
     1210 'Society of Justice Party'
     1211 'Hang Dara Democratic Movement Party'
     1301 'Barisan Nasional'
     1302 'UMNO'
     1303 'MCA'
     1304 'MIC'
     1305 'Gerakan'
     1306 'PBS'
     1307 'PBB'
     1308 'SUPP'
     1309 'Other BN party'
     1310 'People Alliance'
     1311 'PAS'
     1312 'DAP'
     1313 'PKR'
     1314 'PSM'
     1315 'SAPP'
     1316 'SNAP'
     1317 'Other (Termasuk undi rosak)' /
 q33a
     0 'Not applicable'
     1 'Voted for the winning camp'
     2 'Voted for the losing camp'
     8 "Can't choose" /
 q34 q35 q36
     0 'Not applicable'
     1 'Yes '
     2 'No '
     8 "Can't choose"
     9 'Decline to answer' /
 q37
     0 'Not applicable'
     1 'Completely free and fair'
     2 'Free and fair, but with minor problems'
     3 'Free and fair, with major problems'
     4 'Not free or fair'
     5 'Free but unfair'
     8 "Can't choose"
     9 'Decline to answer' /
 q38 q39 q40 q41
     1 'Very Difficult'
     2 'Difficult'
     3 'Easy'
     4 'Very Easy'
     5 'Never Tried'
     8 "Can't choose"
     9 'Decline to answer' /
 q42
     1 'Very safe'
     2 'Safe'
     3 'Unsafe'
     4 'Very unsafe'
     8 "Can't choose"
     9 ' Decline to answer' /
 q43
     1 'Very interested'
     2 'Somewhat interested'
     3 'Not very interested'
     4 'Not at all interested'
     8 "Can't choose"
     9 'Decline to answer' /
 q44
     1 'Everyday'
     2 'Several times a week'
     3 'Once or twice a week'
     4 'Not even once a week'
     5 'Practically never'
     8 "Can't choose"
     9 'Decline to answer' /
 q45
     1 'Almost daily'
     2 'At least once a week'
     3 'At least once a month'
     4 'Several times a year'
     5 'Hardly ever'
     6 'Never'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q46
     1 'Frequently'
     2 'Occasionally'
     3 'Never'
     8 "Can't choose"
     9 'Decline to answer' /
 q47
     95 'Can not choose'
     96 'Decline to answer'
     97 'Do not know'
     98 'No answer'
     99 'Do not feel close to any political party'
     101 'LDP'
     102 'DPJ'
     103 'Komeito(CGP)'
     104 'SDP'
     105 'JCP'
     106 'other party'
     107 'others'
     201 'Democratic Party(HK)'
     202 'DAB(HK)'
     203 'Liberal Party(HK)'
     204 'Civic Party(HK)'
     205 'FTU(HK)'
     206 'ADPL(HK)'
     207 'ADPL(HK)'
     208 'LSD(HK)'
     209 'People Power(HK)'
     210 'NeoDemocrats(HK)'
     211 'NewDemocrats(HK)'
     212 'NWSC(HK)'
     214 'Others(HK)'
     301 'The Uri Party(governing party)'
     302 'The Grand National Party'
     303 'The Democratic Party'
     304 'The Democratic Labor Party'
     305 'The People First Party'
     306 'Other Parties'
     307 'Liberty Forward Party'
     308 'Future hope solidarity'
     309 'Creative Korea Party'
     310 'New Progressive Party'
     311 "People's Participation Party"
     501 'MPRP'
     502 'DP'
     503 'CCP'
     504 'MP'
     505 'RP'
     506 'PP'
     507 'GP'
     508 'other'
     601 'LABAN NG DEMOKRATIKONG PILIPINO'
     602 'LAKAS-NUCD-UMDP'
     603 'LIBERAL PARTY'
     604 'NACIONALISTA PARTY'
     605 "NATIONALIST PEOPLE'S COALITION"
     606 'PARTIDO NG MASANG PILIPINO'
     607 'PDP-LABAN'
     608 'GABRIELA'
     609 'KMP - KILUSAN NG MASANG PILIPINO (GRUPO NI FPJ)'
     610 'GRUPO NI CORY AQUINO'
     611 'PARTIDO NI LACSON'
     612 'PARTIDO NI ROCO'
     613 'ASIAN PACIFIC ELECTRONICS COOPERATIVES'
     614 'PARTIDO NI EDDIE'
     615 'PARTIDO NI VILLANUEVA'
     616 'PARTIDO NI JOEY HIZON'
     617 'PARTIDO NI MAYOR BELMONTE'
     618 'BAYAN MUNA'
     619 'PARTIDO NI ROILO GOLEZ'
     620 'FILIPINO ALLIANCE MOVEMENT SUPPORT GROUP'
     621 'MAYO UNO (LABOR UNION)'
     622 'OPOSISYON'
     623 'PARTIDO NI ESCUDERO'
     624 'ANAK PAWIS'
     625 'SANLAKAS'
     626 'PARTIDO NI MAYOR OREA'
     627 "MAYOR'S QUANO"
     628 'AGAP  hindi ko alam ang ibig sabihin'
     629 'Bangon pilipinas'
     630 'Kapatiran by JC Delos Reyes'
     631 'Magdalo party list'
     632 'Act  alliance of Concerned Teachers'
     633 'Partido ng manggagawa'
     634 'Makamasa'
     635 'Bagong bayan'
     636 'Mayor namin'
     637 'Yung kay Lacson'
     701 'KMT'
     702 'DPP'
     703 'New Party'
     704 'People First Party'
     705 'Taiwan Solidarity Union'
     706 'Other'
     801 'PRAJADHIPAT'
     802 'THAI RAK THAI'
     803 'CHART THAI'
     804 'MAHACHON'
     805 'Other Party'
     806 'Phak Puea Tha'
     807 'Phak Bhum Jai Thai'
     808 'Phak Chart Thai Pattana'
     809 'Phak Pua Paendin'
     901 'Indonesian National Party Marhaenism'
     902 'Social Democrat Labour Party'
     903 'Crescent Star Party'
     904 'Independent Party'
     905 'United Development Party'
     906 'United Democratic Nationhood Party'
     907 'New Indonesia Union Party'
     908 'Freedom Bull National Party'
     909 'Democrat Party'
     910 'Justice and Unity Party'
     911 'Indonesian Democratic Vanguard Party'
     912 'Indonesian United Renaissance People Party'
     913 'National Mandate Party'
     914 'Concern for thel Nation Functional Party'
     915 'National Awakening Party'
     916 'Prosperous and Justice Party'
     917 'Reform Star Party'
     918 'Indonesian Democratic Party-Struggle'
     919 'Peace and Prosperous Party'
     920 'Functional Group Party'
     921 'Patriot Pancasila Party'
     922 'Indonesian Association Party'
     923 'United Regional Party'
     924 'Vanguard Party'
     925 'Partai Hanura'
     926 'Partai Karya Peduli Bangsa (PKPB)'
     927 'Partai Pengusaha dan Pekerja Indonesia'
     928 'Partai Gerindra'
     929 'Partai Barisan Nasional'
     930 'Partai Keadilan dan Persatuan Indonesia'
     931 'Partai Keadilan Sejahtera (PKS)'
     932 'Partai Amanat Nasional (PAN)'
     933 'Partai Kedaulatan'
     934 'Partai Persatuan Daerah (PPD)'
     935 'Partai Kebangkitan Bangsa (PKB)'
     936 'Partai Demokrasi Pembaruan (PDP)'
     937 'Partai Matahari Bangsa'
     938 'Partai Penegak Demokrasi Indonesia'
     939 'Partai Pelopor'
     940 'Partai Golongan Karya'
     941 'Partai Persatuan Pembangunan'
     942 'Partai Damai Sejahtera (PDS)'
     943 'Partai Bulan Bintang (PBB)'
     944 'Partai Demokrasi Indonesia Perjuangan (PDIP)'
     945 'Partai Bintang Reformasi (PBR)'
     946 'Partai Demokrat'
     947 'Partai Indonesia Sejahtera'
     948 'Partai Kebangkitan Nasional Ulama (PKNU)'
     949 'Partai Merdeka'
     950 'Partai Persatuan Nahdlatul Ummah Indonesia'
     951 'Partai Sarikat Indonesia'
     1001 "People's Action Party"
     1002 "The Worker's Party"
     1003 'Singapore Democratic Party'
     1004 'National Solidarity Party'
     1005 "Singapore People's Party"
     1006 'Other'
     1101 'Vietnamese Communist Party'
     1201 "Cambodian People's Party"
     1202 'Sam Rainsy Party'
     1203 'Humanrights Party'
     1204 'Norodom Ranaridh Party'
     1205 'FUNCINPEC Party'
     1206 'Democratic League Party'
     1301 'BarisanNasional'
     1302 'UMNO'
     1303 'MCA'
     1304 'MIC'
     1305 'Gerakan'
     1306 'PBS'
     1307 'PBB'
     1308 'SUPP'
     1309 'Other BN party'
     1310 'Opposition'
     1311 'PAS'
     1312 'DAP'
     1313 'PKR'
     1314 'Other'
     1315 'SAPP'
     1316 'SNAP'
     1317 'Other (Termasuk undi rosak)' /
 q48
     0 'Not applicable'
     1 'Very close'
     2 'Somewhat close'
     3 'Just a little close'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q49 q50 q52 q53 q54 q55 q56 q57 q58 q59 q60 q61 q62 q63 q81 q82 q83 q98 q99 q100 q101 q102 q103 q104 q105 q106 q107 q133 q134 q135 q136 q137 q138 q139 q140 q141 q142 q143 q144 q145 q146 q147 q148
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q51
     0 'Missing'
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q64 q65 q66 q67 q68 q69 q70 q72
     0 'Never Done'
     1 'Once'
     2 'More than once'
     8 "Can't choose"
     9 'Decline to answer' /
 q71
     0 'Never Done'
     1 'Once'
     2 'More than once'
     7 "Don't undersatnd the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q73
     0 'Not applicable (eligible only once)'
     1 'Voted in every election'
     2 'Voted in most elections'
     3 'Voted in some elections'
     4 'Hardly ever voted'
     5 'not eligible to vote'
     8 "Can't choose"
     9 'Decline to answer' /
 q74
     1 'Statement 1. Government leaders implement what voters want'
     2 'Statement 2. Government leaders do what they think is best f'
     7 ' Do not understand the question,'
     8 "Can't choose"
     9 'Decline to answer' /
 q74a q75a q76a q77a q78a q79a
     0 'Not applicable'
     1 'Strongly agree'
     2 'Agree'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q75
     1 'Statement 1. Government is our employee, the people should t'
     2 'Statement 2. The government is like parent, it should decide'
     7 ' Do not understand the question'
     8 " Can't choose"
     9 'Decline to answer' /
 q76
     1 'Statement 1. The media should have the right to publish news'
     2 'Statement 2. The government should have the right to prevent'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q77
     1 'Statement 1. People should look after themselves and be prim'
     2 'Statement 2. The government should bear the main responsibil'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q78
     1 'Statement 1. Political leaders are chosen by the people thro'
     2 'Statement 2. Political leaders are chosen on the basis on th'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q79
     1 'Statement 1. Multiple parties compete to represent political'
     2 'Statement 2. One party represents the interests of all the p'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q80
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q84
     1 'It works fine, not need to change'
     2 'Needs minor change'
     3 'Needs major change'
     4 'Should be replaced'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q85
     1 'Government narrows the gap between the rich and the poor.'
     2 'People choose the government leaders in free and fair electi'
     3 'Government does not waste any public money.'
     4 'People are free to express their political views openly. '
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q86
     1 'The legislature has oversight over the government.'
     2 'Basic necessities, like food, clothes and shelter, are provi'
     3 'People are free to organize political groups.'
     4 'Government provides people with quality public services.'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q87
     1 'Government ensures law and order.'
     2 'Media is free to criticize the things government does.'
     3 'Government ensures job opportunities for all.'
     4 'Multiple parties compete fairly in the election.'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q88
     1 'People have the freedom to take part in protests and demonst'
     2 'Politics is clean and free of corruption.'
     3 'The court protects the ordinary people from the abuse of gov'
     4 'People receive state aid if they are unemployed. '
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q89
     1 'Very satisfied'
     2 'Fairly satisfied'
     3 'Not very satisfied'
     4 'Not at all satisfied'
     8 "Can't choose"
     9 'Decline to answer' /
 q90
     1 'A full democracy'
     2 'A democracy, but with minor problems'
     3 'A democracy, with major problems'
     4 'Not a democracy'
     7 "Don't understand question"
     8 "Can't choose"
     9 'Decline to answer' /
 q91 q92 q93 q94 q120 q121 q122
     97 'Do not understand the question'
     98 "Can't choose"
     99 'Decline to answer' /
 q95
     1 'Very satisfied'
     2 'Somewhat satisfied'
     3 'Somewhat dissatisfied'
     4 'Very dissatisfied'
     8 "Can't choose"
     9 'Decline to answer' /
 q96
     100 'Economics'
     110 'Management of the economy'
     120 'Wages, incomes and salaries'
     130 'Unemployment'
     140 'Poverty/destitution'
     150 'Rates and Taxes'
     160 'Loans / credit'
     170 'Land privatization'
     180 'Inflation'
     190 'International trade'
     191 'Basic necessities (price of fuel, rice, cooking oil, and sal'
     200 'Food / Agriculture'
     210 'Farming / agriculture'
     220 'Food shortage/famine'
     230 'Drought'
     240 'Land'
     250 'Environmental protection'
     260 'Natural resources'
     300 'Infrastructure'
     310 'Transportation'
     320 'Communications'
     330 'Infrastructure / roads'
     400 'Government Services'
     410 'Education'
     420 'Technology'
     430 'Housing'
     440 'Electricity'
     450 'Water supply'
     460 'Orphans/street children/homeless children'
     470 'Social security/ social welfare'
     480 'Services (other)'
     500 'Medical treatment'
     510 'Health care'
     520 'AIDS'
     530 'Sickness / Disease'
     540 'Public sanitation'
     550 'Food and drug safety'
     600 'Governance'
     610 'Crime/ personal safety'
     620 'Corruption'
     630 'Political violence'
     640 'Political instability/political divisions/ ethnic tensions'
     650 'Discrimination/ inequality'
     660 'Gender issues/women¡¦s rights'
     670 'Democracy/political rights'
     680 'Failure or ineffectiveness of political system'
     690 'Government efficacy'
     691 'Constitutional government'
     692 'Budget deficit'
     693 'Administration of justice'
     694 'Administrative procedure'
     695 'Administrative neutrality'
     696 'Irresponsible leaders or government'
     700 'General social or political situation'
     710 'Immigration'
     720 'Social problems (suicide, divorce, moral decline)'
     730 'Ageing population, declining birthrate'
     740 'Population growth'
     750 'Cultural issues in the face of social change'
     751 'Religious issues'
     752 'Cultural preservation'
     760 'War (international)'
     770 'Civil war'
     780 'External relations, diplomacy'
     790 'Terrorism'
     791 'National defense'
     800 'Taiwan¡¦s unique problems'
     801 'Military procurement, national defense'
     802 'Name rectification'
     803 'Cross-strait issue'
     804 'Referendum'
     805 'Problems in operation of democratic institutions'
     806 'Gangsterism'
     807 'Political parties'
     808 'Foreign laborers'
     809 'National Sovereignty'
     810 'Justic'
     811 'Mining exploration'
     812 'Border conflict between Cambodia and Thailand'
     901 'The people¡¦s livelihood'
     902 'Media turmoil'
     903 'Disparity between the rich and the poor'
     904 'These problems are all important'
     905 'Maintenance and management of public facilities'
     906 'Industrial transformation'
     907 'Technology drain'
     908 'Illegal drugs'
     909 'Uneven development across urban and rural'
     930 'Restoration from Tohoku earthquake'
     940 'Management and compensation for the nuclear accident'
     950 'Territorial problem'
     960 'Controversy over the constitution'
     970 'The emperor system and the royal family'
     980 'Depopulation of the countryside'
     990 'no problems'
     995 'other issues'
     998 "Can't choose"
     999 'Decline to answer' /
 q97
     0 'Not applicable'
     1 'Very likely'
     2 'Likely'
     3 'Not very likely'
     4 'Not at all likely'
     8 "Can't choose"
     9 'Decline to answer' /
 q108 q109 q110 q111
     1 'Always'
     2 'Most of the time'
     3 'Sometimes'
     4 'Rarely'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q112
     1 'Very capable'
     2 'Capable'
     3 'Not capable'
     4 'Not at all capable'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q113
     1 'Very responsive'
     2 'Largely responsive'
     3 'Not very responsive'
     4 'Not responsive at all'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q114
     1 'Most people'
     2 'Quite a lot of people'
     3 'Some people'
     4 'Few people'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q115
     1 'A good deal'
     2 'Quite a lot'
     3 'Not much'
     4 'Not at all'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q116 q117
     1 'Hardly anyone is involved'
     2 'Not a lot of officials are corrupt'
     3 'Most officials are corrupt'
     4 'Almost everyone is corrupt'
     8 "Can't choose"
     9 'Decline to answer' /
 q118
     1 'It is doing its best'
     2 'It is doing something'
     3 'It is not doing much'
     4 'Doing nothing'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q119
     0 'Not applicable'
     1 'Witnessed'
     2 'Never witnessed'
     6 'No one I know has personally witnessed'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q119_1 q119_2 q119_3
     0 'Not applicable'
     1 'Yes'
     2 'No'
     6 'N/o one I know has personally witnessed'
     7 'Do not understand'
     8 "Can't choose"
     9 'Decline to answer' /
 q123
     90 'Missing'
     97 'Do not understand the question'
     98 "Can't choose"
     99 'Decline to answer' /
 q124
     1 'Democracy is always preferable to any other kind of governme'
     2 'Under some circumstances, an authoritarian government can be'
     3 'For people like me, it does not matter whether we have a dem'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q125
     1 'Democracy is capable of solving the problems of our society'
     2 "Democracy cannot solve our society's problems"
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q126
     1 'Economic development is definitely more important'
     2 'Economic development is somewhat more important'
     3 'Democracy is somewhat more important'
     4 'Democracy is definitely more important'
     5 'They are both equally important'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q127
     1 'Reducing economic inequality is definitely more important'
     2 'Reducing economic inequality is somewhat more important'
     3 'Protecting political freedom is somewhat more important'
     4 'Protecting political freedom is definitely more important'
     5 'They are both equally important'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q128 q152 q153
     1 'Strongly agree'
     2 'Agree'
     3 'Disagree'
     4 'Strongly disagree'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q129 q130 q131 q132
     1 'Strongly approve'
     2 'Somewhat approve'
     3 'Somewhat disapprove'
     4 'Strongly disapprove'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q149
     1 'Very closely'
     2 'Somewhat closely'
     3 'Not too closely'
     4 'Very little'
     5 'Not at all'
     8 "Can't choose"
     9 'Decline to answer' /
 q150
     1 'Almost daily'
     2 'At least once a week'
     3 'At least once a month'
     4 'Several times a year'
     5 'Hardly ever'
     6 'Never'
     8 "Can't choose"
     9 'Decline to answer' /
 q151
     1 'Strongly agree'
     2 'Somewhat Agree'
     3 'Somewhat Disagree'
     4 'Strongly disagree'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q154
     1 'Very proud'
     2 'Somewhat proud'
     3 'Not very proud'
     4 'Not proud at all'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q155
     1 'Very willing'
     2 'Willing'
     3 'Not willing'
     4 'Not willing at all'
     7 "Don't understand the question"
     8 "Can't choose"
     9 'Decline to answer' /
 q156
     1 'China'
     2 'Japan'
     3 'India'
     4 'United States'
     5 'Other'
     6 'Taiwan'
     7 'Singapore'
     8 'European Union'
     9 'South Korea'
     10 'China and Japan'
     11 'China and India'
     12 'Australia'
     13 'Association of Southeast Asian Nations, ASEAN'
     14 'North Korea'
     15 'China and United States'
     16 'Commonwealth of Independent States, CIS'
     17 'United States and Japan'
     18 'Vietnam'
     19 'Philippines'
     20 'Canada'
     21 'United Arab Emirates'
     22 'Malaysia'
     23 'Hong Kong'
     24 'Thailand'
     25 'Russia'
     26 'Cambodia'
     27 'Indonesia'
     90 'Not applicable'
     97 'Do not understand the question'
     98 "Can't choose"
     99 'Decline to answer' /
 q157 q157a
     0 'Not applicable'
     1 'Much more good than harm'
     2 'Somewhat more good than harm'
     3 'Somewhat more harm than good'
     4 'Much more harm than good'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q158
     1 'China'
     2 'Japan'
     3 'India'
     4 'United States'
     5 'Other'
     6 'Taiwan'
     7 'Singapore'
     8 'European Union'
     9 'South Korea'
     10 'China and Japan'
     11 'China and India'
     12 'Australia'
     13 'Association of Southeast Asian Nations, ASEAN'
     14 'North Korea'
     15 'China and United States'
     16 'Commonwealth of Independent States, CIS'
     17 'United States and Japan'
     18 'Vietnam'
     19 'Philippines'
     20 'Canada'
     21 'United Arab Emirates'
     22 'Malaysia'
     23 'Hong Kong'
     24 'Thailand'
     25 'Cambodia'
     26 'France'
     27 'Mongolia'
     90 'Not applicable'
     97 'Do not understand the question'
     98 "Can't choose"
     99 'Decline to answer' /
 q159
     1 'United States'
     2 'China'
     3 'India'
     4 'Japan'
     5 'Singapore'
     6 'Other'
     7 'We should follow our country¡¦s own model'
     8 'China and Singapore'
     9 'Japan and Singapore'
     10 'Germany'
     11 'Switzerland'
     12 'South Korea'
     13 'United States, Japan and Singapore'
     14 'United States and Japan'
     15 'Finland'
     16 'Canada'
     17 'Netherlands'
     18 'Sweden'
     19 'United States and Singapore'
     20 'Canada and New Zealand'
     21 'Northern Europe'
     22 'New Zealand'
     23 'Bhutan'
     24 'Vietnam'
     25 'United Kingdom'
     26 'Germany and Finland'
     27 'European countries'
     28 'Switzerland and Denmark'
     29 'Taiwan'
     30 'Indonesia'
     31 'Saudi Arabia'
     32 'United Arab Emirates'
     33 'Israel'
     34 'Australia'
     35 'Norway'
     36 'France'
     37 'North Korea'
     38 'Malaysia'
     39 'Thailand'
     40 'Russian'
     90 'Not applicable'
     97 'Do not understand the question'
     98 "Can't choose"
     99 'Decline to answer' /
 q160
     1 'A great deal of influence'
     2 'Some influence'
     3 'Not much influence'
     4 'No influence at all'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 q161
     0 'Not applicable'
     1 'Very positive'
     2 'Positive'
     3 'Somewhat positive'
     4 'Somewhat negative'
     5 'Negative'
     6 'Very negative'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 se2 ir2a
     1 'Male'
     2 'Female' /
 se4
     1 'Single/Never married'
     2 'Married'
     3 'Living-in as married'
     4 'Widowed'
     5 'Separated/Married but separated/not living with legal spouse'
     6 'Divorced'
     9 'Decline to answer' /
 se5
     1 'No formal education'
     2 'Incomplete primary/elementary'
     3 'Complete primary/elementary'
     4 'Incomplete secondary/high school: technical/vocational type'
     5 'Complete secondary/high school: technical/vocational type'
     6 'Incomplete secondary/high school'
     7 'Complete secondary/high school'
     8 'Some university education'
     9 'University education completed'
     10 'Post-graduate degree'
     98 "Can't choose"
     99 'Decline to answer' /
 se5a
     90 'Not applicable'
     97 'No answer'
     98 'Cannot choose'
     99 'Decline to answer' /
 se6
     1 'Traditional folk religion (Shenism)'
     10 'Roman Catholic'
     20 'Protestant'
     21 'Seventh Day Adventist'
     22 'Baptist'
     23 'Pentecostal'
     24 'Evangelical'
     25 'Epescopal'
     26 'Methodist'
     27 'Grace Gospel of Church'
     28 'Jesus christle'
     29 'Jesus chris is lord'
     30 'Jews'
     40 'Islam'
     41 'Shia'
     42 'Sunni'
     50 'Hindu'
     60 'Buddhist'
     61 'Taoism and Buddhist'
     62 'Tenrikyo'
     63 'Buddhist, Roman Catholic and Protestant'
     64 'Cosmology'
     65 'Seicho'
     70 'Other Asian religions'
     71 'Sikhism'
     72 'Iglesia Ni Cristo'
     73 'Aglipayan'
     74 'Born Again'
     75 'Shinto'
     76 'Taoism'
     77 'I-Kuan Tao'
     78 'Confucianism'
     79 'Tiruray'
     80 'Other'
     81 'Jehovah Witness'
     82 'Mormons'
     83 'Dating Daan'
     84 'Anglican'
     85 "Baha'i"
     86 'Animism'
     87 'Soka association'
     88 'Iglesia filipina independente'
     90 'None'
     98 'Cannot choose'
     99 'Decline to answer'
     100 'Decline to answer' /
 se7
     1 'Several times a day'
     2 'Once a day'
     3 'Several times a week'
     4 'Once a week'
     5 'Several times a month'
     6 'Once a month'
     7 'Only during festivals (or several times a year)'
     8 'Once a year'
     9 'Less often'
     10 'Practically never'
     11 'No religion'
     90 'Not applicable'
     98 'Cannot choose'
     99 'Decline to answer' /
 se7a
     1 'Very religious'
     2 'Moderately religious'
     3 'Lightly religious'
     4 'Not religious at all'
     90 'Not applicable'
     98 "Can't choose"
     99 'Decline to answer' /
 se8a se8c se8d
     98 "Can't choose"
     99 'Decline to answer' /
 se8b
     1 'One generation'
     2 'Two generations'
     3 'Three generations'
     4 'More than three generations'
     8 "Can't choose"
     9 'Decline to answer' /
 se9
     1 'Employed'
     2 'Not employed'
     9 'Decline to answer' /
 se9a
     0 'Not applicable'
     1 'Self-employed or business owner'
     2 'Working in family business'
     3 'Working for an outside employer'
     4 'Peasant/farmer'
     9 'Decline to answer' /
 se9b
     0 'Not applicable'
     1 'No employees'
     2 '1-9 employees'
     3 '10+ employees'
     9 'Decline to answer' /
 se9c
     1 'Higher service'
     2 'Lower service'
     3 'Routine clerical/sales'
     4 'Small employers'
     5 'Independent'
     7 'Manual foremen'
     8 'Skilled manual'
     9 'Semi-Unskilled manual'
     10 'Farm workers'
     11 'Farmers/Farm managers'
     12 'Not working'
     9990 'Not applicable'
     9999 'Decline to answer' /
 se9d se10d
     0 'Not applicable'
     1 'Yes (Currently unemployed but seeking work)'
     2 'No (Not currently employed and not seeking work)'
     3 'Never employed'
     9 'Decline to answer' /
 se9e
     1 'homemaker'
     2 'student'
     3 'retired'
     4 'person with disabilities'
     5 'unemployed'
     6 'Other'
     9 "don't wanna do anything"
     10 'sick at home'
     90 'not appilcable'
     99 'decline to answear' /
 se10
     1 'Yes'
     2 'No'
     8 "Can't choose"
     9 'Decline to answer' /
 se10_1
     0 'Not applicable'
     1 'Employed'
     2 'Not employed'
     8 "Can't choose"
     9 'Decline to answer' /
 se10a
     0 'Not applicable'
     1 'Self-employed or business owner'
     2 'Working in family business'
     3 'Working for an outside employer'
     4 'Peasant/farmer'
     9 'Decline to answer' /
 se10b
     0 'Not applicable'
     1 'No employees'
     2 '1-9 employees'
     3 '10+ employees'
     8 "Don't know"
     9 'Decline to answer' /
 se10c
     1 'Higher service'
     2 'Lower service'
     3 'Routine clerical/sales'
     4 'Small employers'
     5 'Independent'
     7 'Manual foremen'
     8 'Skilled manual'
     9 'Semi-Unskilled manual'
     10 'Farm workers'
     11 'Farmers/Farm managers'
     12 'Not working'
     9990 'Not applicable'
     9998 "Can't not choose"
     9999 'Decline to answer' /
 se10e
     1 'homemaker'
     2 'student'
     3 'retired'
     4 'person with disabilities'
     5 'unemployed'
     6 'Others'
     7 'landlord'
     8 'volunteer'
     9 "don't wanna do anything"
     10 'sick at home'
     90 'not appilcable'
     99 'decline to answer' /
 se11
     1 'Only local language '
     2 'Mostly local language'
     3 'A mixture of local and official language'
     4 'Mostly official language'
     5 'Only official language'
     6 'Others'
     8 "Can't choose"
     9 'Decline to answer' /
 se12
     1 'Lowest status'
     2 '...'
     3 '...'
     4 '...'
     5 '...'
     6 '...'
     7 '...'
     8 '...'
     9 '...'
     10 'Highest status'
     97 "Don't understand"
     98 "Can't choose"
     99 'Decline to answer' /
 se13
     1 'Lowest level'
     2 'Low level'
     3 'Middle level'
     4 'High level'
     5 'Highest level'
     8 "Can't choose"
     9 'Decline to answer' /
 se13a
     0 'Not applicable'
     1 'Our income covers the needs well, we can save.'
     2 'Our income covers the needs all right, without much difficul'
     3 'Our income does not cover the needs, there are difficulties.'
     4 'Our income does not cover the needs, there are great difficu'
     7 'Do not understand the question'
     8 "Can't choose"
     9 'Decline to answer' /
 se14a se14b se14c se14d se14e se14f se14g se14h se14i se14j se14k se14l se14m se14n se14o
     0 'Not applicable'
     1 'Yes'
     2 'No'
     9 'Decline to answer' /
 ir2
     1 'Yes'
     2 'No'
     90 'Not applicable' /
 ir2b
     90 'Not applicable/Not the first interview'
     99 'Decline to answer' /
 ir2c
     201 'Mostly Cantonese'
     401 'Official Language'
     402 'Dialects'
     501 'Mongolia'
     601 'Bicolano'
     602 'Cebuano'
     603 'English'
     604 'Ilocano'
     605 'Ilonggo'
     606 'Tagalog'
     611 'Maranao'
     612 'Masbate'
     613 'Waray'
     614 'Kankanaey'
     615 'Pangasinense'
     701 'Mostly official language'
     702 'A mixture of Min-nan and official language'
     703 'A mixture of Hakka and official language'
     704 'A mixture of Min-nan and Hakka language'
     705 'Mostly Min-nan language'
     706 'Mostly Hakka language'
     801 'Official language'
     802 'Northern language'
     803 'Esan language'
     804 'Southern language'
     805 'Yawee language'
     806 'Other'
     901 'Indonesian Language'
     902 'Javanese Language'
     903 'Sundanese Language'
     904 'Madurese Language'
     905 'Other local language'
     1001 'English'
     1002 'Mandarin'
     1003 'Chinese dialect'
     1004 'Malay'
     1006 'Other'
     1101 'Vietnammese'
     1201 'Khmer'
     1301 'Bahasa Bidayuh'
     1302 'Bahasa Dusun dan Melayu'
     1303 'Bahasa Iban'
     1304 'Bahasa Melayu'
     1305 'Bahasa Melayu dan Dialek Kelantan'
     1306 'Bahasa Melayu dan Dialek Utara'
     1307 'Bahasa Melayu dan Dusun'
     1308 'Bahasa Melayu dan Inggeris'
     1309 'Bahasa Melayu Sarawak'
     1310 'Bahasa Melayu, Dialek'
     1311 'Kelantan dan Pahang'
     1312 'Bahasa Tamil'
     1313 'Dialek Kedah' /
 ir3
     1 'Yes (Go to Q3a)'
     2 'No (Go to Q4)' /
 ir3a
     0 'None'
     1 "Respondent's spouse"
     2 'Children'
     3 'Parents or parents-in-law'
     4 'Neighbors/Passers by'
     5 'Party/Government Official'
     6 'Friends'
     7 'Brothers/ Sisters'
     9 'Others' /
 ir3a_1HK ir3a_2HK ir3a_3HK ir3a_4HK ir3a_5HK
     0 'No'
     1 'Yes' /
 ir4
     1 'Yes. Right at the beginning of the interview'
     2 'Yes. In the middle of the interview'
     3 'Yes. Towards the end of the interview'
     4 'Never'
     9 'Decline to answer' /
 ir5
     1 'Never'
     2 'Occasionally'
     3 'Sometimes'
     4 'Always'
     9 'Decline to answer' /
 ir6
     1 'Highly cooperative'
     2 'Fairly cooperative'
     3 'Not very cooperative'
     9 'Decline to answer' /
 ir7
     1 'Highly sincerely'
     2 'Fairly sincere'
     3 'Not very sincere'
     4 'Highly insincerely'
     9 'Decline to answer' /
 ir8
     0 "Can't determine"
     1 'All'
     2 'Most'
     3 'Some'
     4 'Few'
     5 'None'
     9 'Decline to answer' /
 ir10
     1 'Native language or dialect(mother tongue)'
     2 'The main language of the country but not the native language'
     3 'The main language of the region/localities but not the antiv'
     4 'others'
     90 'Not applicable' /
 ir10a
     1 'Yes'
     2 'No' /
 ir11a
     1 'Wide enough for car and paved with asphalt, cement or man-ma'
     2 'Not wide enough for car, but paved with asphalt, cement or m'
     3 'Paved with stone'
     4 'Unpaved/dirt road'
     5 'Muddy'
     6 'Others'
     9 'Decline to answer' /
 ir11b
     1 'Tap water inside the house'
     2 'Shared tap water in the public place'
     3 'Handbump for groundwater'
     4 'Shared handbump for groundwater'
     5 'From river, pound or lake'
     6 'other'
     9 'Decline to answer' /
 ir11c
     1 'Yes'
     2 'No'
     9 'Decline to answer' /
 ir11d
     1 'Less than 10 minutes by walking'
     2 'Less than 20 minutes'
     3 'Less than 40 minutes'
     4 'Less than an hour'
     5 'Less than two hours'
     6 'Less than three hours'
     7 'Less than four hours'
     8 'More than fours hours'
     9 'Decline to answer' /
 ir12
     1 'Walking'
     2 'Easy driving'
     9 "Can't determine"
     90 'Not applicable' /
 ir12a ir12b ir12c ir12d ir12e ir12f ir12g ir12h ir12i
     0 'No'
     1 'Yes'
     9 "Can't determine" /
 ir12k
     0 'No'
     1 'Yes'
     9 "Can't determine" /
 ir13
     1 'Capital or Megacity (1 million population plus)'
     2 'Regional center or Other major cities (100,000 plus)'
     3 'Small city or town (less than 100,000 people)'
     4 'Village or countryside'
     9 "Can't determine" /
 INCOMEALL
     9999990 'Not Applicable'
     9999998 "Don't Know"
     9999999 'Decline to answer' / .


SAVE OUTFILE='C:\users\peiru\desktop\new folder (6)\13_countries\abs3w_cn.sav'.
