

library(mi)
data(nlsyV)
mdf <- missing_data.frame(nlsyV)
show(mdf)
mdf <- change(mdf, y = c("income", "momrace"), what = "type", to = c("non", "un"))
show(mdf)
summary(mdf)
image(mdf)
hist(mdf)
rm(nlsyV)
options(mc.cores = 4)
imputations <- mi(mdf, n.iter = 30, n.chains = 4, max.minutes = 20)
show(imputations)
round(mipply(imputations, mean, to.matrix = TRUE), 3)
Rhats(imputations)
imputations <- mi(imputations, n.iter = 5)
plot(imputations)
image(imputations)
summary(imputations)
analysis <- pool(ppvtr.36 ~ first + b.marr + income + momage + momed + momrace, data = imputations, m = 5)
display(analysis)
dfs <- complete(imputations, m = 2)
